name: Automation test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Check Maven Version
      - name: Check Maven Version
        run: mvn -version

      # Set up Java (Uses Java 17)
      - name: Set JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # SetUp Chrome Driver
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get remove --purge google-chrome-stable || true
          wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_134.0.6998.165-1_amd64.deb
          sudo dpkg -i google-chrome-stable_134.0.6998.165-1_amd64.deb
          google-chrome --version

      # Installing Chromedriver matching the installed chrome version
      - name: Install ChromeDriver
        run: |
            wget https://storage.googleapis.com/chrome-for-testing-public/134.0.6998.165/linux64/chromedriver-linux64.zip
            unzip chromedriver-linux64.zip
            sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
            sudo chmod +x /usr/bin/chromedriver
            chromedriver --version

      # Cache Maven Dependencies for faster Builds
      - name: Cache maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys:
            ${{ runner.os }}-maven-

      # Run Maven tests
      - name: Run maven Test
        run: mvn clean test

      # Upload Cucumber Reports
      - name: Upload Cucumber Reports
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-reports
          path: target/cucumber-reports/

      - name: Deploy Cucumber Report
        if: always()  # Upload even if tests fail
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/cucumber-html-reports/  # Path to your HTML report
          publish_branch: gh-pages